import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import PageContainer from '../components/PageContainer'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContainer>
        
      </PageContainer>
    </>
  )
}

export default Home
